export const fuze_config = {
	keys: [
		{ name: 'name', weight: 0.7 },
		{ name: 'title', weight: 0.7 },
		{ name: 'description', weight: 0.5 },
		{ name: 'home_title', weight: 0.3 },
		{ name: 'home_subtitle', weight: 0.3 },
		{ name: 'price', weight: 0.3 },
		{ name: 'country', weight: 0.2 },
		{ name: 'city', weight: 0.2 },
		{ name: 'street', weight: 0.1 },
		{ name: 'postcode', weight: 0.1 },
		{ name: 'dishes.name', weight: 0.6 },
		{ name: 'dishes.description', weight: 0.4 },
		{ name: 'dishes.ingredients.name', weight: 0.6 },
	],
	threshold: 0.3,
	location: 0,
	distance: 100,
	includeMatches: true,
	includeScore: true,
	useExtendedSearch: true,
	shouldSort: true,
}
