import './styles/globals.css'
import Head from "next/head";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
    <Head>
      <link rel="stylesheet" href="https://use.typekit.net/npl8ujx.css"/>
    </Head>
      <body>{children}</body>
    </html>
  )
}
